import { Navbar } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ weight: ["400", "700"], subsets: ['latin'], fallback: ['sans-serif'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className='wrapper pt-wrapperTop bg-bgBlackTan'>
          <div className="container pt-containerTop">
            <Navbar />
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
