import { Navbar } from '@/components'
import './globals.css'
import { poppins } from '@/fonts'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className='wrapper pb-wrapperPaddingBottom bg-bgBlackTan'>
          <div className="container pt-containerPaddingTop">
            <Navbar />
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
